### ISSUE TITLE
Code does not uglify

### ISSUE THREAD

**Issue by tremby** [mc-zone/react-event-emitter-mixin#2]
When running this module through Uglifyjs, we hit an error.

```
Unexpected token punc «(», expected punc «:» [./~/react-event-emitter-mixin/EventEmitterMixin.js:10,0]
```

It looks like invalid JS.

It's the same just running it through Uglifyjs on the command line and also when it goes through webpack, with babel and react enabled.

https://github.com/mc-zone/react-event-emitter-mixin/blob/master/EventEmitterMixin.js#L9

**Comment by mc-zone** [comment]
@tremby Sorry for my late! 
This error is because I use ES2015 and forgot to transform it. my fault. 
I've compile file by Babel and update to the master. Feel free to use it and I will republish to npm a little while.
Welcome for more reply If you still have other problems. :smile:

**Comment by mc-zone** [comment]
Have update new version to [Release](https://github.com/mc-zone/react-event-emitter-mixin/releases) and [NPM](https://www.npmjs.com/package/react-event-emitter-mixin).

**Comment by tremby** [comment]
Oh, I see. I think this actually means it was a configuration problem my end, rather than anything you should have changed on your end.

I had webpack set up to run only *.jsx files through Babel/React, so it wasn't translating this library. Still on version 0.0.3, I've just built again but allowing Babel/React to run over all .js/.jsx files, and it builds and uglifies just fine.

If I were you I'd probably roll back and remove the compiled version from the package. Smaller diffs, less confusing for potential contributors, less to remember to do when preparing new releases, etc. You could still include the compiled but only in the NPM releases, by having it automatically compiled and included during the publish operation, if you like. But given that it's a react module I think it's perfectly reasonable to have the main script in your package.json point to ES2015/JSX code.

**Comment by mc-zone** [comment]
Sure you can, but I think it would be better to keep a compiled file. Because you don't need include `node_modules` in Babel compile path in your project, it will make your compile task slowly.
For example when you are using Webpack, the best practice on your [`module.loaders`](http://webpack.github.io/docs/configuration.html#module-loaders) is often set the `include` only to your own source code or just set the `exclude: /node_modules/` .
So keep a compiled is maybe more friendly to use. And we can just use Gulp-task do build things efficiently.(like transform with Babel).

> Is your code just ES2015, or is it JSX? (I'm actually new to React; I'm just configuring this for the front-end developer.) If it's JSX it might be a nice hint to people like me to call the file itself *.jsx.

Just used some ES2015 function shorthand, no JSX.

**Comment by tremby** [comment]
I did previously have it ignoring `node_modules`, but there were other modules distributed only in JSX.

That aside, there's still no reason to check in compiled code. You can have it generated with a `prepublish` command and sent up to npm so people who install it have it precompiled, still without it being in version control.

**Comment by mc-zone** [comment]
I thought about it, you are right. I've remove it from version control, and make a dist dir (with gitignore) to deal with build and release next time.
