### ISSUE TITLE
Transform source into ES5

### ISSUE THREAD

**Issue by Andreyco** [mc-zone/react-event-emitter-mixin#4]
Transform source into ES5 so that it does not require changes to build settings. In many cases, node_modules are excluded from being transformed anyways.

**Comment by andrewkmin** [comment]
Is this deprecated now for ES6?

**Comment by mc-zone** [comment]
@Andreyco Sorry for late. I've publish the compiled `dist` file since @0.0.6. Now you can reinstall and use the latest version.

**Comment by mc-zone** [comment]
@andrewkmin Maybe you can use [react-mixin](https://github.com/brigand/react-mixin) which allows you to use mixin with ES6 classes.
